import os, requests, pyotp, time
import pandas as pd
from SmartApi import SmartConnect
from datetime import datetime, timedelta

API_KEY = os.getenv("ANGEL_API_KEY")
CLIENT_ID = os.getenv("ANGEL_CLIENT_ID")
PASSWORD = os.getenv("ANGEL_PASSWORD")
TOTP_SECRET = os.getenv("ANGEL_TOTP_SECRET")

obj = SmartConnect(api_key=API_KEY)
clean = TOTP_SECRET.strip().replace(" ","").upper()
obj.generateSession(CLIENT_ID, PASSWORD, pyotp.TOTP(clean).now())

master = requests.get("https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json", timeout=30).json()
token_map = {d['symbol'].replace('-EQ',''): d['token'] for d in master if d.get('exch_seg')=='NSE' and str(d.get('symbol','')).endswith('-EQ')}

# FINAL SMALLCAP 360 UNIQUE LIST
STOCKS = ["360ONE","AADHARHFC","AAVAS","ABSLAMC","AEGISLOG","AFFLE","AARTIIND","ABFRL","ADANIGREEN","ADANIPOWER","AJANTPHARM","AKZOINDIA","ALEMBICLTD","ALKYLAMINE","AMBER","ANANDRATHI","ANGELONE","ANURAS","APARINDS","APLAPOLLO","APLLTD","APTUS","ARCHEAN","ASAHIINDIA","ASTERDM","ASTRAL","ATUL","AUBANK","AVANTIFEED","AVANTEL","BALAMINES","BALKRISIND","BALRAMCHIN","BANDHANBNK","BANKINDIA","BATAINDIA","BAYERCROP","BDL","BEML","BHEL","BIKAJI","BIOCON","BIRLACORPN","BLUEDART","BLUESTARCO","BSE","CAMS","CAMPUS","CAPLIPOINT","CARBORUNIV","CARTRADE","CASTROLIND","CCL","CEAT","CENTRALBK","CERA","CESC","CGCL","CHALET","CHAMBLFERT","CHEMPLASTS","CHENNPETRO","CHOICEIN","CHOLAFIN","CLEAN","COCHINSHIP","COFORGE","CRAFTSMAN","CREDITACC","CROMPTON","CSBBANK","CUB","CUPID","CYIENT","DATAPATTNS","DBCORP","DCBBANK","DEEPAKFERT","DEEPAKNTR","DELTACORP","DEVYANI","EASEMYTRIP","EDELWEISS","EICHERMOT","ELECON","ELGIEQUIP","EMBASSYDEV","ENDURANCE","EQUITASBNK","ERIS","EXIDEIND","FDC","FEDERALBNK","FINEORG","FSL","GABRIEL","GARFIBRES","GESHIP","GHCL","GLENMARK","GMRINFRA","GNFC","GODREJPROP","GRANULES","GRAPHITE","GRINDWELL","GRSE","GSFC","GSPL","GULFOILLUB","HAPPSTMNDS","HFCL","HINDCOPPER","HOMEFIRST","HONASA","HUDCO","IEX","IDBI","IDFCFIRSTB","IIFL","INDIACEM","INDIAMART","INDIANB","INDIGO","INDOCO","INDUSINDBK","INTELLECT","IOB","IPCALAB","IRCON","IRFC","JBCHEPHARM","JINDALSTEL","JUBLINGREA","JUBLFOOD","JUSTDIAL","JYOTHYLAB","KAJARIACER","KALYANKJIL","KARURVYSYA","KEC","KEI","KFINTECH","KPITTECH","KRBL","KPRMILL","KIMS","LATENTVIEW","LAURUSLABS","LEMONTREE","LTF","MANAPPURAM","MANYAVAR","MASTEK","MAXHEALTH","MCX","MEDANTA","METROPOLIS","MFSL","MOTHERSON","MOIL","MRPL","MUTHOOTFIN","NAM-INDIA","NATIONALUM","NAUKRI","NBCC","NCC","NH","NHPC","NMDC","NOCIL","NUVAMA","OBEROIRLTY","OLECTRA","ONWARDTEC","PEL","PERSISTENT","PETRONET","PFIZER","PHOENIXLTD","PNBHOUSING","PNCINFRA","POLYCAB","POLYMED","PRAJIND","PRESTIGE","PVRINOX","QUESS","RADICO","RAIN","RAILTEL","RALLIS","RBLBANK","REDINGTON","RITES","ROUTE","RVNL","SAIL","SAPPHIRE","SBICARD","SBFC","SOBHA","SONACOMS","SOUTHBANK","STLTECH","SUZLON","SYNGENE","TATACHEM","TATACOMM","TEJASNET","THOMASCOOK","TITAGARH","TRIDENT","TVSMOTOR","UJJIVANSFB","UNOMINDA","VOLTAS","WELCORP","YESBANK","ZEEL","ZENSARTECH","ZYDUSLIFE","BLS","DELHIVERY","DMART","FIVESTAR","GLAND","GRINFRA","LICHSGFIN","METROBRAND","NAZARA","NYKAA","POONAWALLA","TATATECH","UTIAMC","VIJAYA","ZOMATO"]

print(f"Total Smallcap 400 Loaded: {len(STOCKS)}")

# इथून पुढे तुझा जुना Backtest Logic जसाच्या तसा ठेव...
