# V25 NSE 1000 SMALL+MIDCAP ULTRA FAST - 60 SEC - 67 LOGIC
import os,requests,pyotp,pandas as pd,time
from SmartApi import SmartConnect
from datetime import datetime,timedelta
from concurrent.futures import ThreadPoolExecutor,as_completed

API_KEY=os.getenv("ANGEL_API_KEY","").strip();CLIENT_ID=os.getenv("ANGEL_CLIENT_ID","").strip()
PASSWORD=os.getenv("ANGEL_PASSWORD","");TOTP_SECRET=os.getenv("ANGEL_TOTP_SECRET","").strip().replace(" ","").upper()
BOT_TOKEN=os.getenv("TELEGRAM_BOT_TOKEN","");CHAT_ID=os.getenv("TELEGRAM_CHAT_ID","")
MAX_TRADES=8;MAX_ACTIVE=2;ACTIVE=[];TOTAL=0

# NSE 1000 SMALL + MIDCAP - FULL LIST - LIQUID FILTERED
ALL_SYMBOLS="""RELIANCE TCS HDFCBANK ICICIBANK INFY ITC SBIN BHARTIARTL LT BAJFINANCE MARUTI TITAN SUNPHARMA WIPRO ULTRACEMCO NTPC POWERGRID TATAMOTORS TATASTEEL JSWSTEEL HCLTECH BAJAJFINSV ASIANPAINT ONGC ADANIENT ADANIPORTS COALINDIA GRASIM HINDALCO HINDUNILVR CIPLA DIVISLAB DRREDDY EICHERMOT BPCL BRITANNIA HEROMOTOCO ICICIPRULI SBILIFE HDFCLIFE LTIM TRENT VEDL INDUSINDBK AXISBANK KOTAKBANK BAJAJ-AUTO APOLLOHOSP TATACONSUM NESTLEIND JSWENERGY NHPC SJVN GMRINFRA IDFCFIRSTB FEDERALBNK AUBANK INDIANB BANKINDIA UNIONBANK CANBK MAHABANK PNB BANKBARODA RECLTD PFC IRFC RVNL IRCTC HAL BEL BHEL SAIL TATAPOWER ADANIGREEN ADANIPOWER IDEA YESBANK SUZLON JIOFIN ZOMATO NYKAA PAYTM POLICYBZR DELHIVERY NAUKRI INDIAMART LTF MUTHOOTFIN MANAPPURAM CHOLAFIN SHRIRAMFIN TATACHEM DEEPAKNTR AARTIIND ATUL SRF PIIND UPL COROMANDEL ABB SIEMENS VOLTAS DIXON TATATECH TATAELXSI KPITTECH COFORGE PERSISTENT MPHASIS LTTS IEX MCX BSE CAMS CDSL ANGELONE DLF GODREJPROP DMART POLYCAB HAVELLS INDHOTEL M&M TVSMOTOR MOTHERSON MRF MAZDOCK BDL DAMCAPITAL HUDCO ALOKINDS CENTRALBK COCHINSHIP AARTIDRUGS AAVAS ABSLAMC AFFLE AIAENG AJANTPHARM AKZOINDIA ALEMBICLTD ALKYLAMINE ANANDRATHI ANANTRAJ APARINDS APTUS ASAHIINDIA ASTERDM ASTRAL ATGL AVANTIFEED AWL BALAMINES BANDHANBNK BAYERCROP BBTC BLUEDART BSOFT CANFINHOME CAPLIPOINT CARBORUN CASTROLIND CCL CEATLTD CERA CGCL CRAFTSMAN CREDITACC CRISIL CSBBANK CUB CYIENT DABUR DALBHARAT DCAL DCBBANK EASEMYTRIP ELGIEQUIP EMAMILTD EQUITASBNK ERIS EXIDEIND FINEORG FINCABLES FSL GALAXYSURF GESHIP GILLETTE GLAXO GLENMARK GMDCLTD GODREJCP GRANULES GRAPHITE GRINDWELL GUJALKALI GUJGASLTD HAPPSTMNDS HONASA IIFL INTELLECT IOC ISEC JBCHEPHARM JINDALSAW JUBLINGREA JUSTDIAL JYOTHYLAB KAJARIA KARURVYSYA KEC KIRLOSENG KRBL KSB KTKBANK LALPATHLAB LATENTVIEW MAPMYINDIA MARICO MASTEK MAXHEALTH MEDANTA METROPOLIS MGL NAVINFLUOR NCC NETWEB NH OFSS PATANJALI PETRONET PFIZER PIDILITIND PNCINFRA POLYMED PRAJIND PRINCEPIPE PVRINOX QUESS RADICO RAILTEL RALLIS RAMCOCEM RATNAMANI RAYMOND RBLBANK RELAXO SAPPHIRE SCHAEFFLER SEQUENT SHANKARA SHREECEM SKFINDIA SOLARINDS STAR STLTECH SUDARSCHEM SUMICHEM SUNTECK SUPREMEIND SUVENPHAR SYNGENE SYRMA TATACOMM TATAMTRDVR TEAMLEASE TECHNOE TEJASNET THOMASCOOK TIINDIA TIMKEN TIPSMUSIC TITAGARH TMB TNPL TRIDENT TRITURB TTKPRESTI UCOBANK UNOMINDA UTIAMC VGUARD VTL WELCORP WELSPUNLTD WESTLIFE ZYDUSLIFE IRB MANINFRA GRSE RVNL BEML ASTRAZEN ZFCVINDIA PTC MOTILALOFS NAM-INDIA KFINTECH PNBHOUSING SWSOLAR ADANIPOWER ABFRL GMRINFRA RPOWER RCOM IFCI JPASSOCIAT SUZLON YESBANK RBLBANK BANDHANBNK FEDERALBNK IDFCFIRSTB UJJIVANSB EQUITASBNK SOUTHBANK KARURVYSYA CUB DCBBANK IDBI PNB CANBK UNIONBANK BANKINDIA INDIANB MAHABANK CENTRALBK UCOBANK IOB PSB BANKBARODA J&KBANK RBLBANK AUBANK INDIAMART JUSTDIAL NAUKRI AFFLE MAPMYINDIA LATENTVIEW EASEMYTRIP IRCTC NYKAA PAYTM ZOMATO DELHIVERY POLICYBZR CLEAN SCIENCE FINEORG GALAXYSURF AARTIIND ATUL DEEPAKNTR NAVINFLUOR SRF PIIND UPL COROMANDEL SUMICHEM AARTIDRUGS ANUP ALKYLAMINE BALAMINES GHCL TATACHEM GNFC GSFC CHAMBLFERT RCF FACT NFL DEEPAKFERT GODREJAGRO AVANTIFEED WATERBASE APEX VENKEYS BAJAJHIND BALRAMCHIN DWARKESH DHAMPUR SAKHTISUG TRIVENI UTTAM SUGAR RENUKA RAJSREESUG KCP KCP SUGAR EIDPARRY ANDHRSUGAR JUBLINGREA JUBLPHARMA JUBLINDS GRANULES LAURUSLABS NATCOPHARM AUROPHARMA CIPLA DRREDDY DIVISLAB SUNPHARMA LUPIN ZYDUSLIFE BIOCON SYNGENE STAR STRIDES ERIS JBCHEPHARM GLENMARK ALEMBICLTD AJANTPHARM TORRENT ALKYLAMINE MARKSANS WOCKPHARMA IPCA AJANTA AARTIPHARM LINDEINDIA PRAJIND THERMAX TRITURB KIRLOSENG KIRLOSKAR CUMMINS ABB SIEMENS VOLTAS BLUESTAR WHIRLPOOL DIXON AMBER PGEL EPACK DURABLE KAYNES SYRMA CENTUM AVALON Syrma ELGIEQUIP GRINDWELL CARBORUN WELD FORGE TRIVENI KSB KIRLOSBROS ESAB TIMKEN SKFINDIA SCHAEFFLER SHANTIGEAR ELECON Pitti RATNAMANI MAHSEAMLES JINDALSAW APLAPOLLO JSL JSLHISAR WELSPUNLTD WELCORP RATNAMANI JINDALSTEL SAIL NMDC HINDCOPPER HINDZINC VEDL NALCO MOIL SAIL JSWSTEEL TATASTEEL JSWENERGY TATAPOWER ADANIGREEN ADANIPOWER NTPC POWERGRID NHPC SJVN THERMAL IEX PTC CESC TORRENT POWER RELINFRA ADANITRANS TATAPOWER JSWENERGY ADANIGREEN KPI GREEN SUZLON INOXWIND BHEL BEL HAL MAZDOCK COCHINSHIP GRSE BDL MIDHANI BEML ASTRA MICRO SIDHANT PARAS ANTGRAPHIDE LTEMR MRF CEAT APOLLOTYRE JK TYRE MRF BALKRISIND TVS SRICHAKRA WHEELS MOTHERSON SONACOMS M&M MARUTI EICHERMOT TVSMOTOR BAJAJ-AUTO HEROMOTOCO ASHOKLEY BHARATFORG MOTHERSON ENDURANCE MINDACORP SUBROS JTEKT SANDHAR GABRIEL MINDACORP VARROC BHARATFORG TATAMOTORS ASHOKLEY ESCORTS VST TAFE SWARAJ BEML TITAGARH TEXRAIL JWL BEML RAILTEL IRFC IRCON RVNL IRCTC CONCOR GATEWAY GATI TCI BLUEDART VRL MAHLOG ALL CARGO NAVNETEDUL DHANDHOO TCIEXPRESS SIS SDBL SIS TEAMLEASE QUESS FIRSTSOURCE ECLERX AFFLE INTELLECT COFORGE MPHASIS LTTS TATAELXSI KPITTECH PERSISTENT CYIENT HCLTECH INFY WIPRO LTIM TECHM MASTEK SONATASOFT BSOFT ZENSAR HEXAWARE BIRLASOFT ROUTE TANLA AURIONPRO NEWGEN INTELLECT MATS BSE MCX CDSL CAMS KFINTECH ANANDRATHI MOTILALOFS IIFL 360 ONE NUVAMA JMFINANCIAL EDELWEISS ANGELONE SMC CHOICE INTL GEOJIT ARMANFIN APTUS AAVAS HOMEFIRST CANFINHOME REPCO GICRE PNBHOUSING LICHSGFIN AADHAR AAVAS APTUS ABSLAMC UTIAMC NAM-INDIA HDFCAMC ADAMC BAJHLDG BAJAJFINSV SHRIRAMFIN CHOLAFIN MUTHOOTFIN MANAPPURAM LTF IIFL FINANCE M&MFIN CIFL SUNDARMFIN POOJAWEST ISEC SBILIFE HDFCLIFE ICICIPRULI ICICIGI STARHEALTH GICRE NIACLIC HAPPSTMNDS TATATECH TATACHEM TATACOMM TATAMTRDVR TATAPOWER TATASTEEL TATACONSUM TATAMOTORS TATACHEM TATAINVEST TATAMTRDVR TITAN VOLTAS TRENT WESTLIFE DMART TRENT ADITYA ABFRL ARVIND RAYMOND VEDL PAGEIND LUX GOCOLORS KPR MILLER WELSPUNLTD WELCORP ALKYLAMINE GOKEX TRIDENT HIMATSEIDE WELSPUNLTD VTL VGUARD POLYCAB KEI FINCABLES HAVELLS BAJAJELEC CROMPTON VOLTAS WHIRLPOOL BLUESTAR DIXON AMBER PGEL SYRMA KAYNES CENTUM ELIN EPACK SENCO TBZ THANGAMAYIL KALYANKJIL TITAN RAJESHEXPO TBZ SENCO PCJEWELLER JEWELLERY TRIBHOVANDAS MANAPPURAM MUTHOOTFIN DPABRASIVE GOLDIAM BHAGYANAGAR RAJESHEXPO""".split()

def tg(m):
 try:requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",data={"chat_id":CHAT_ID,"text":m},timeout=5)
 except:pass
 print(m,flush=True)

obj=SmartConnect(api_key=API_KEY);obj.generateSession(CLIENT_ID,PASSWORD,pyotp.TOTP(TOTP_SECRET).now())
UNIQUE=list(set(ALL_SYMBOLS))
tg(f"🚀 V25 NSE 1000 START {datetime.now().strftime('%H:%M')} | {len(UNIQUE)} STOCKS | 67 LOGIC | ULTRA FAST")

def get_tokens():
 try:
  df=pd.read_json("https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json")
  d={r['symbol'].replace('-EQ',''):str(r['token']) for _,r in df.iterrows() if r['exch_seg']=='NSE' and str(r['symbol']).endswith('-EQ')}
  return {s:d[s] for s in UNIQUE if s in d}
 except:return{}
TOKENS=get_tokens()

def indi(df):
 c=df["close"];df["ema9"]=c.ewm(9).mean();df["ema15"]=c.ewm(15).mean();df["ema21"]=c.ewm(21).mean();df["ema50"]=c.ewm(50).mean()
 df["vwap"]=(c*df["volume"]).cumsum()/df["volume"].cumsum();df["macd"]=c.ewm(12).mean()-c.ewm(26).mean()
 df["macd_sig"]=df["macd"].ewm(9).mean();d=c.diff();g=d.where(d>0,0).rolling(14).mean();l=-d.where(d<0,0).rolling(14).mean()
 df["rsi"]=100-(100/(1+g/l));df["vol20"]=df["volume"].rolling(20).mean();return df

def scan_one(sym):
 token=TOKENS.get(sym)
 if not token:return None
 try:
  p={"exchange":"NSE","symboltoken":token,"interval":"FIVE_MINUTE","fromdate":(datetime.now()-timedelta(days=2)).strftime("%Y-%m-%d 09:15"),"todate":datetime.now().strftime("%Y-%m-%d %H:%M")}
  d=obj.getCandleData(p)
  if not d or not d.get('data'):return None
  df=pd.DataFrame(d['data'],columns=['date','open','high','low','close','volume'])
  if len(df)<25:return None
  if df["volume"].iloc[-15:].mean()<20000:return None # Pre-filter fast
  df=indi(df);last=df.iloc[-1];prev=df.iloc[-2];ltp=last["close"];do=df["open"].iloc[-1];pc=df["close"].iloc[-2]
  dh=df["high"].iloc[-1];dl=df["low"].iloc[-1];dg=(ltp-do)/do*100;gap=(do-pc)/pc*100 if pc else 0
  if abs(gap)>6:return None
  m5=(ltp-prev["close"])/prev["close"]*100;rec=(ltp-dl)/dl*100
  v20=df["volume"].iloc[-1]/last["vol20"] if last["vol20"]>0 else 1;v5=df["volume"].iloc[-1]/df["volume"].iloc[-6:-1].mean() if len(df)>6 else 1
  high_52=df["high"].max();near_52h=(ltp/high_52)*100;low_52=df["low"].min();near_52l=(ltp/low_52)*100
  buy=0;sell=0;br=[];sr=[]
  if last["ema9"]>last["ema15"]>last["ema21"]:buy+=1.5;br.append("TREND UP")
  if last["ema9"]<last["ema15"]<last["ema21"]:sell+=1.5;sr.append("TREND DN")
  if ltp>last["vwap"]:buy+=1.2;br.append("VWAP+")
  else:sell+=1.2;sr.append("VWAP-")
  if last["macd"]>last["macd_sig"]:buy+=1.2;br.append("MACD+")
  else:sell+=1.2;sr.append("MACD-")
  if 55<=last["rsi"]<=72:buy+=1.0;br.append(f"RSI B {last['rsi']:.0f}")
  if 28<=last["rsi"]<=50:sell+=1.0;sr.append(f"RSI S {last['rsi']:.0f}")
  if dg>=0.5:buy+=1.2;br.append(f"DAY+{dg:.1f}%")
  if dg<=-0.5:sell+=1.2;sr.append(f"DAY{dg:.1f}%")
  if m5>=0.15:buy+=1.0;br.append(f"5M+{m5:.2f}%")
  if m5<=-0.15:sell+=1.0;sr.append(f"5M{m5:.2f}%")
  if ltp>=dh*0.994:buy+=1.2;br.append("NEAR HIGH")
  if rec>=1.0:buy+=1.0;br.append(f"REC {rec:.1f}%")
  if m5>=0.5 and rec>=1.0:buy+=2.5;br.append("BOUNCE")
  if v20>=2.5:buy+=2.5 if dg>0 else 0; sell+=2.5 if dg<0 else 0; br.append(f"VOL {v20:.1f}x") if dg>0 else sr.append(f"VOL {v20:.1f}x")
  if v5>=2.0 and ltp>=dh*0.992:buy+=3.5;br.append("DAY-H BLAST")
  if last["vwap"]>last["ema9"]>last["ema15"]:buy+=3.5;br.append("VWAP>9>15 SUPER")
  if last["vwap"]<last["ema9"]<last["ema15"]:sell+=3.5;sr.append("VWAP<9<15 SUPER")
  if near_52h>=98:buy+=4.0;br.append(f"52W-H {near_52h:.1f}%")
  if near_52l<=102:sell+=4.0;sr.append(f"52W-L {near_52l:.1f}%")
  if near_52h>=98 and v20>=3 and dg>=2:buy+=5.0;br.append("JACKPOT 🚀")
  if buy>=3 and buy>sell+0.5:
   cl=df["low"].iloc[-3:].min();min_sl=1.0 if ltp<200 else 0.8;sl_p=ltp*(1-min_sl/100);sl=min(cl,sl_p) if (ltp-cl)/ltp*100>=min_sl else sl_p;sl_pct=(ltp-sl)/ltp*100
   return {"side":"BUY","symbol":sym,"entry":ltp,"sl":round(sl,2),"t1":round(ltp*(1+sl_pct/100),2),"t2":round(ltp*(1+sl_pct*1.5/100),2),"slp":round(sl_pct,2),"reason":"|".join(br),"score":buy}
  if sell>=3 and sell>buy+0.5:
   ch=df["high"].iloc[-3:].max();min_sl=1.0 if ltp<200 else 0.8;sl_p=ltp*(1+min_sl/100);sl=max(ch,sl_p) if (ch-ltp)/ltp*100>=min_sl else sl_p;sl_pct=(sl-ltp)/ltp*100
   return {"side":"SELL","symbol":sym,"entry":ltp,"sl":round(sl,2),"t1":round(ltp*(1-sl_pct/100),2),"t2":round(ltp*(1-sl_pct*1.5/100),2),"slp":round(sl_pct,2),"reason":"|".join(sr),"score":sell}
 except:return None

# ULTRA FAST 100 WORKERS - NSE 1000
s=datetime.now()
cnt=0
with ThreadPoolExecutor(max_workers=100) as ex:
 fut={ex.submit(scan_one,s):s for s in UNIQUE}
 for f in as_completed(fut):
  r=f.result();cnt+=1
  if cnt%200==0:print(f"Scanned {cnt}/1000 - {(datetime.now()-s).total_seconds():.0f}s")
  if r:tg(f"🚀 NSE1000 {r['side']} {r['symbol']} @{r['entry']} SL {r['sl']}({r['slp']}%) T1 {r['t1']} T2 {r['t2']} | {r['reason']} S:{r['score']:.1f} | 1000 SMALL+MID | 67 LOGIC")
  if TOTAL>=8:break
tg(f"⚡ NSE 1000 SCAN DONE {(datetime.now()-s).total_seconds():.0f}s | Found {cnt} | {len(UNIQUE)} STOCKS")
